name: Sync SPDX taxonomy

on:
  push:
    paths:
      - 'taxonomy'
  workflow_dispatch:

jobs:
  generate-keywords:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout parent repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Get submodule URL and SHAs
        id: info
        run: |
          echo "curr=$(git rev-parse HEAD:taxonomy)" >> $GITHUB_OUTPUT
          echo "prev=$(git log -1 --pretty=format:%P -- taxonomy | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "url=$(git config -f .gitmodules --get submodule.taxonomy.url)" >> $GITHUB_OUTPUT

      - name: Clone current taxonomy
        run: |
          git clone --quiet ${{ steps.info.outputs.url }} taxonomy-curr
          cd taxonomy-curr
          git checkout ${{ steps.info.outputs.curr }}

      - name: Clone previous taxonomy (best-effort)
        continue-on-error: true
        run: |
          if [ -n "${{ steps.info.outputs.prev }}" ]; then
            git clone --quiet ${{ steps.info.outputs.url }} taxonomy-prev
            cd taxonomy-prev
            git checkout ${{ steps.info.outputs.prev }} || echo "Prev commit not reachable"
          fi

      - name: Determine new YAML files
        run: |
          mkdir -p detection/rules
          touch new_files.txt
          if [ -d taxonomy-prev/.git ]; then
            diff -qr taxonomy-prev taxonomy-curr | \
              grep "^Only in taxonomy-curr" | grep ".yaml" | \
              sed 's|.*taxonomy-curr/||' > new_files.txt || true
          else
            # Si no hay versión previa alcanzable, todos los YAML son "nuevos"
            find taxonomy-curr -name '*.yaml' > new_files.txt
          fi
          cat new_files.txt

      - name: Create keyword definition files
        run: |
          while read -r file; do
            [ -z "$file" ] && continue
            ID=$(yq '.id' "taxonomy-curr/$file")
            if [ -n "$ID" ] && [ ! -f "detection/rules/${ID}.yaml" ]; then
              cat > "detection/rules/${ID}.yaml" <<EOF
          id: $ID
          keywords:
            - $ID
          EOF
                        echo "Created detection/rules/${ID}.yaml"
                      fi
                    done < new_files.txt

      - name: Commit and create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add keyword definitions for new SPDX algorithms"
          branch: spdx-sync/${{ github.run_id }}
          title: "Add keyword definitions for new SPDX algorithms"
          body: "Automatically generated keyword definition files for new algorithms detected in SPDX taxonomy submodule."
          labels: "automation,spdx-sync"
