name: Sync SPDX taxonomy

on:
  push:
    paths:
      - 'taxonomy'   # se dispara cuando cambia el puntero del submódulo
  workflow_dispatch:

jobs:
  generate-keywords:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Identify commits
        id: find_shas
        run: |
          CURR_SHA=$(git rev-parse HEAD:taxonomy)
          echo "curr=$CURR_SHA" >> $GITHUB_OUTPUT
          PREV_SHA=$(git log -1 --pretty=format:%P -- taxonomy | cut -d' ' -f1)
          echo "prev=$PREV_SHA" >> $GITHUB_OUTPUT

      - name: Get submodule URL
        id: sub_url
        run: |
          URL=$(git config -f .gitmodules --get submodule.taxonomy.url)
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Clone full taxonomy repo
        run: |
          git clone --quiet --no-tags --progress ${{ steps.sub_url.outputs.url }} full-taxonomy

      - name: Find new YAML files
        run: |
          PREV="${{ steps.find_shas.outputs.prev }}"
          CURR="${{ steps.find_shas.outputs.curr }}"
          cd full-taxonomy
          if [ -z "$PREV" ]; then
            git ls-files '*.yaml' > ../new_files.txt
          else
            git fetch --all --quiet
            git diff --name-only --diff-filter=A $PREV $CURR -- '*.yaml' > ../new_files.txt
          fi
          cd ..
          cat new_files.txt

      - name: Create keyword definition files
        run: |
          mkdir -p detection/rules
          while read -r file; do
            [ -z "$file" ] && continue
            echo "Processing $file"
            ID=$(yq '.id' "full-taxonomy/$file")
            if [ -n "$ID" ] && [ ! -f "detection/rules/${ID}.yaml" ]; then
              cat > "detection/rules/${ID}.yaml" <<EOF
            id: $ID
            keywords:
              - $ID
            EOF
                      echo "Created detection/rules/${ID}.yaml"
                    fi
                  done < new_files.txt

      - name: Commit and create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add keyword definitions for new SPDX algorithms"
          branch: spdx-sync/${{ github.run_id }}
          title: "Add keyword definitions for new SPDX algorithms"
          body: "Automatically generated keyword definition files for new algorithms detected in SPDX taxonomy submodule."
          labels: "automation,spdx-sync"
